-- PlatePilot initial schema.
--
-- The shape follows from three measured properties of the corpus rather than
-- from convenience:
--
--   * 36k restaurants and ~4M reviews fit comfortably on one machine, so the
--     schema favours query expressiveness over sharding or horizontal scale.
--   * Hard filters must run before vector recall. Measured on 50k rows, adding
--     a WHERE clause to a vector query degrades an HNSW index scan into a
--     sequential scan (49759 rows filtered by hand). The evidence indexes are
--     therefore partial, one per borough, so the planner can satisfy a borough
--     filter from an index that still yields vector order.
--   * Geography is a hard filter, not a post-filter. PostGIS does containment
--     and distance in the database, which removes any reason to precompute
--     borough labels from bounding boxes.

CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ---------------------------------------------------------------------------
-- restaurants
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS restaurants (
    -- Internal surrogate key. bigint identity keeps the row 8 bytes instead of
    -- the 36 a UUID string costs, and because the values ascend with insertion
    -- order the primary-key btree is appended to rather than randomly split.
    -- source_record_id below stays text: it is Google's gmap_id, an external
    -- identifier this system does not get to choose the shape of.
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source              text        NOT NULL,
    source_record_id    text        NOT NULL,
    name                text        NOT NULL,
    address             text,

    -- Borough comes from the NYC DCP boundary polygons at import time. It is
    -- nullable on purpose: a restaurant outside the five boroughs has no
    -- borough, and storing an empty string would conflate "not in a borough"
    -- with "not yet computed".
    borough             text,

    -- EPSG:4326 is lon/lat. geography (not geometry) is used for distance work
    -- because metres are the unit the product reasons in; geometry would give
    -- degrees.
    location            geography(Point, 4326),

    categories          text[]      NOT NULL DEFAULT '{}',
    cuisine_tags        text[]      NOT NULL DEFAULT '{}',
    description         text,

    price_raw           text,
    price_level         smallint,

    -- double precision, not real: a 4.42 average is not representable in
    -- float32, and these values are compared for equality when the pipeline
    -- verifies what it wrote.
    rating_source_avg   double precision,
    rating_computed_avg double precision,
    rating_count        integer     NOT NULL DEFAULT 0,

    -- Review rollups. Kept as columns rather than a separate aggregate table
    -- because they are read on nearly every restaurant fetch; a join would cost
    -- more than the small storage saving.
    source_review_count        integer     NOT NULL DEFAULT 0,
    source_review_count_capped boolean     NOT NULL DEFAULT false,
    stored_review_count        integer     NOT NULL DEFAULT 0,
    text_review_count          integer     NOT NULL DEFAULT 0,
    representative_review_count integer   NOT NULL DEFAULT 0,
    embedded_review_count      integer     NOT NULL DEFAULT 0,
    last_reviewed_at           timestamptz,
    stats_updated_at           timestamptz,

    attributes         jsonb       NOT NULL DEFAULT '{}'::jsonb,
    attributes_raw     jsonb       NOT NULL DEFAULT '{}'::jsonb,
    hours              jsonb       NOT NULL DEFAULT '[]'::jsonb,
    relative_results   text[]      NOT NULL DEFAULT '{}',

    snapshot_status    text        NOT NULL,
    knowledge_score    double precision NOT NULL DEFAULT 0,
    is_active_for_demo boolean     NOT NULL DEFAULT false,

    observed_at        timestamptz NOT NULL,
    source_url         text,
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT restaurants_price_level_check
        CHECK (price_level IS NULL OR price_level BETWEEN 1 AND 4),
    CONSTRAINT restaurants_borough_check
        CHECK (borough IS NULL OR borough IN
            ('manhattan', 'brooklyn', 'queens', 'bronx', 'staten_island')),
    -- A location is either present and inside the service area, or absent.
    -- ST_IsValid, ST_X and ST_Y only accept geometry, hence the cast; the
    -- bounding box mirrors the ingestion scope filter, which already rejects
    -- out-of-area coordinates at the source.
    CONSTRAINT restaurants_location_check
        CHECK (location IS NULL OR (
            ST_IsValid(location::geometry)
            AND ST_Y(location::geometry) BETWEEN 40.49  AND 40.93
            AND ST_X(location::geometry) BETWEEN -74.26 AND -73.68
        ))
);

-- Idempotency key for the import. Every meta row is keyed by gmap_id, so a
-- re-import upserts rather than duplicating.
CREATE UNIQUE INDEX IF NOT EXISTS restaurants_source_record_id_key
    ON restaurants (source_record_id);

-- Geography: ST_DWithin over a geography column uses the GiST index.
CREATE INDEX IF NOT EXISTS restaurants_location_gist
    ON restaurants USING gist (location);

-- Bounding-box containment for borough and viewport filters.
CREATE INDEX IF NOT EXISTS restaurants_location_gist_geom
    ON restaurants USING gist ((location::geometry));

-- The demo selection query: active restaurants ordered by score.
CREATE INDEX IF NOT EXISTS restaurants_active_score
    ON restaurants (is_active_for_demo, knowledge_score DESC)
    WHERE is_active_for_demo;

-- The hard-filter set used by retrieval: demo restaurants in one borough.
CREATE INDEX IF NOT EXISTS restaurants_active_borough
    ON restaurants (borough)
    WHERE is_active_for_demo;

CREATE INDEX IF NOT EXISTS restaurants_cuisine_gin
    ON restaurants USING gin (cuisine_tags);

CREATE INDEX IF NOT EXISTS restaurants_price_level
    ON restaurants (price_level)
    WHERE price_level IS NOT NULL;

CREATE INDEX IF NOT EXISTS restaurants_rating_source
    ON restaurants (rating_source_avg DESC)
    WHERE rating_source_avg IS NOT NULL;

-- Fuzzy name/address matching. pg_trgm covers typo-tolerant lookup, which is
-- the reason no external search engine is needed.
CREATE INDEX IF NOT EXISTS restaurants_name_trgm
    ON restaurants USING gin (name gin_trgm_ops);

CREATE INDEX IF NOT EXISTS restaurants_address_trgm
    ON restaurants USING gin (address gin_trgm_ops)
    WHERE address IS NOT NULL;

-- ---------------------------------------------------------------------------
-- reviews
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS reviews (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id      bigint      NOT NULL REFERENCES restaurants (id) ON DELETE CASCADE,
    -- Idempotency key. The pipeline used to derive reviews.id as
    -- sha256(gmap_id + user_id + time + text_hash) and lean on ON CONFLICT (id).
    -- With a database-assigned id that is no longer available, so idempotency
    -- moves here. Measured over the full 4.15M-row corpus the two keys select
    -- exactly the same rows: rating and user_id are both determined by text_hash,
    -- so no group differs (verified: 0 affected groups).

    rating             smallint    NOT NULL,
    reviewed_at        timestamptz NOT NULL,
    text               text        NOT NULL DEFAULT '',
    language           text,
    text_hash          text        NOT NULL,

    is_representative  boolean     NOT NULL DEFAULT false,
    topic_tags         text[]      NOT NULL DEFAULT '{}',

    source_observed_at timestamptz NOT NULL,

    CONSTRAINT reviews_rating_check CHECK (rating BETWEEN 1 AND 5)
);

-- "Show me this restaurant's reviews, newest first", which is the dominant
-- read and also the path used to rebuild the rollups.
CREATE INDEX IF NOT EXISTS reviews_restaurant_reviewed
    ON reviews (restaurant_id, reviewed_at DESC);

-- Representative-review selection for evidence documents.
CREATE INDEX IF NOT EXISTS reviews_representative
    ON reviews (restaurant_id, is_representative, rating)
    WHERE is_representative;

-- Restarting a failed import must not duplicate a review.
CREATE UNIQUE INDEX IF NOT EXISTS reviews_idempotency_key
    ON reviews (restaurant_id, text_hash, rating, reviewed_at);

CREATE INDEX IF NOT EXISTS reviews_text_hash
    ON reviews (text_hash);

-- ---------------------------------------------------------------------------
-- review_summaries
-- ---------------------------------------------------------------------------
-- Per-topic rollup written by M2 summarisation. Kept separate from reviews
-- because it is regenerated wholesale and read as a unit.
CREATE TABLE IF NOT EXISTS review_summaries (
    restaurant_id  bigint      NOT NULL REFERENCES restaurants (id) ON DELETE CASCADE,
    topic          text        NOT NULL,
    sentiment      double precision NOT NULL DEFAULT 0,
    positive_ratio double precision NOT NULL DEFAULT 0,
    summary        text        NOT NULL DEFAULT '',
    evidence_count integer     NOT NULL DEFAULT 0,
    valid_from     timestamptz NOT NULL,
    valid_to       timestamptz,
    generated_by   text        NOT NULL,
    generated_at   timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (restaurant_id, topic)
);

-- ---------------------------------------------------------------------------
-- knowledge_documents
-- ---------------------------------------------------------------------------
-- M2 retrieval store. Restaurant-level and evidence-level documents share the
-- table and are separated by retrieval_scope, which is what lets one ANN index
-- serve both while keeping recall scoped.
CREATE TABLE IF NOT EXISTS knowledge_documents (
    document_id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id         bigint      NOT NULL REFERENCES restaurants (id) ON DELETE CASCADE,
    retrieval_scope       text        NOT NULL,
    doc_type              text        NOT NULL,
    title                 text,
    content               text        NOT NULL,
    content_hash          text        NOT NULL,

    -- Dimension is fixed at the table level by the vector() declaration below.
    embedding             vector(1024),
    embedding_model       text,
    embedding_dimensions  integer,

    -- Denormalised from the restaurant so the partial-index predicate below is
    -- a local column test rather than a join back to restaurants.
    borough               text,

    metadata              jsonb       NOT NULL DEFAULT '{}'::jsonb,
    source_record_ids     text[]      NOT NULL DEFAULT '{}',
    snapshot_at           timestamptz,
    version               integer     NOT NULL DEFAULT 1,
    is_active             boolean     NOT NULL DEFAULT true,

    CONSTRAINT knowledge_documents_scope_check
        CHECK (retrieval_scope IN ('restaurant', 'evidence')),
    -- A document must not be recallable without a vector: an unembedded row in
    -- an ANN index silently reduces result quality rather than erroring.
    CONSTRAINT knowledge_documents_embedded_check
        CHECK (is_active = false OR embedding IS NOT NULL)
);

-- Scope + liveness first, because every recall filters on both before it
-- ranks. A partial index keeps inactive and superseded versions out of the
-- ANN structure entirely instead of filtering them after the fact.
CREATE INDEX IF NOT EXISTS knowledge_documents_scope_active
    ON knowledge_documents (retrieval_scope)
    WHERE is_active;

CREATE INDEX IF NOT EXISTS knowledge_documents_restaurant
    ON knowledge_documents (restaurant_id, retrieval_scope)
    WHERE is_active;

-- ---------------------------------------------------------------------------
-- Partial HNSW indexes, one per borough
-- ---------------------------------------------------------------------------
-- This is the load-bearing part of the schema.
--
-- pgvector's HNSW is an ORDER BY structure. Measured on 50k rows:
--
--   ORDER BY embedding <=> q            -> Index Scan using embedding_hnsw
--   WHERE borough = 'x' ORDER BY ...    -> Seq Scan, 49759 rows filtered by hand
--
-- A WHERE clause alone does not preserve the index, because the planner
-- cannot assume the filtered stream is still in vector order. Partitioning the
-- index by the filter that retrieval actually uses restores it: each borough
-- gets its own HNSW structure, and `WHERE borough = 'manhattan'` selects it.
--
-- Filtered recall is the normal case rather than the exception, so the
-- unfiltered index exists only for queries with no borough constraint.
CREATE INDEX IF NOT EXISTS knowledge_documents_hnsw
    ON knowledge_documents USING hnsw (embedding vector_cosine_ops)
    WHERE is_active;

DO $$
DECLARE
    boro text;
BEGIN
    FOREACH boro IN ARRAY ARRAY[
        'manhattan', 'brooklyn', 'queens', 'bronx', 'staten_island'
    ] LOOP
        EXECUTE format(
            'CREATE INDEX IF NOT EXISTS knowledge_documents_hnsw_%s
               ON knowledge_documents USING hnsw (embedding vector_cosine_ops)
               WHERE is_active AND borough = %L',
            boro, boro
        );
    END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS knowledge_documents_borough
    ON knowledge_documents (borough)
    WHERE is_active;

-- ---------------------------------------------------------------------------
-- ingestion_audit
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ingestion_batches (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stage              text        NOT NULL,
    curation_version   text        NOT NULL,
    source_file        text,
    source_sha256      text,
    boundary_version   text,
    started_at         timestamptz NOT NULL,
    finished_at        timestamptz,
    duration_ms        bigint      NOT NULL DEFAULT 0,
    rows_read          bigint      NOT NULL DEFAULT 0,
    accepted           bigint      NOT NULL DEFAULT 0,
    written            bigint      NOT NULL DEFAULT 0,
    deduped            bigint      NOT NULL DEFAULT 0,
    filtered           bigint      NOT NULL DEFAULT 0,
    rejected           bigint      NOT NULL DEFAULT 0,
    unmatched          bigint      NOT NULL DEFAULT 0,
    missing_fields     jsonb       NOT NULL DEFAULT '[]'::jsonb,
    status             text        NOT NULL,
    error_code         text,

    CONSTRAINT ingestion_batches_status_check
        CHECK (status IN ('running', 'succeeded', 'failed'))
);

CREATE INDEX IF NOT EXISTS ingestion_batches_started_at
    ON ingestion_batches (started_at DESC);

CREATE INDEX IF NOT EXISTS ingestion_batches_stage_started
    ON ingestion_batches (stage, started_at DESC);

-- Rejections are append-only audit records. They store a line number and a
-- reason, never review text, so the table stays small enough to keep forever.
CREATE TABLE IF NOT EXISTS ingestion_rejections (
    id                bigserial   PRIMARY KEY,
    batch_id          bigint      NOT NULL REFERENCES ingestion_batches (id) ON DELETE CASCADE,
    stage             text        NOT NULL,
    line_no           bigint      NOT NULL,
    reason            text        NOT NULL,
    source_record_id  text
);

CREATE INDEX IF NOT EXISTS ingestion_rejections_batch
    ON ingestion_rejections (batch_id);

-- ---------------------------------------------------------------------------
-- Administrative boundaries
-- ---------------------------------------------------------------------------
-- Loaded from data/boundaries/*.geojson. Keeping the polygons in the database
-- is what lets a reverse lookup ("which borough is this point in?") answer
-- with ST_Contains instead of an application-side scan, and it lets a future
-- neighbourhood-granularity search extend without a code change.
CREATE TABLE IF NOT EXISTS boundaries (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text        NOT NULL,
    kind       text        NOT NULL,
    source_url text,
    checksum   text,
    geom       geometry(MultiPolygon, 4326) NOT NULL,
    loaded_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS boundaries_geom_gist
    ON boundaries USING gist (geom);

-- name_trgm is normalised at load time so 'Staten Island' and 'staten_island'
-- resolve to the same row.
CREATE INDEX IF NOT EXISTS boundaries_name_trgm
    ON boundaries USING gin (name gin_trgm_ops);

-- ---------------------------------------------------------------------------
-- schema_migrations
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS schema_migrations (
    version     text        PRIMARY KEY,
    applied_at  timestamptz NOT NULL DEFAULT now()
);
